### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by joemccann** [dabit3/openai-functions-god-app#1]
```sh

> gpt-functions@0.1.0 start
> next start

- ready started server on 0.0.0.0:3000, url: http://localhost:3000
Error: Could not find a production build in the '/Users/asymmetricholdingsltd./dev/chatgpt/openai-functions-god-app/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
    at NextNodeServer.getBuildId (/Users/asymmetricholdingsltd./dev/chatgpt/openai-functions-god-app/node_modules/next/dist/server/next-server.js:349:23)
    at new Server (/Users/asymmetricholdingsltd./dev/chatgpt/openai-functions-god-app/node_modules/next/dist/server/base-server.js:152:29)
    at new NextNodeServer (/Users/asymmetricholdingsltd./dev/chatgpt/openai-functions-god-app/node_modules/next/dist/server/next-server.js:173:9)
    at NextServer.createServer (/Users/asymmetricholdingsltd./dev/chatgpt/openai-functions-god-app/node_modules/next/dist/server/next.js:179:24)
    at async /Users/asymmetricholdingsltd./dev/chatgpt/openai-functions-god-app/node_modules/next/dist/server/next.js:200:31
    at async NextServer.prepare (/Users/asymmetricholdingsltd./dev/chatgpt/openai-functions-god-app/node_modules/next/dist/server/next.js:160:24)
    at async Server.<anonymous> (/Users/asymmetricholdingsltd./dev/chatgpt/openai-functions-god-app/node_modules/next/dist/server/lib/render-server.js:124:17) {
  type: 'Error'
}

```

**Comment by datashaman** [comment]
Do as the error says and build the app first, the docs are missing that.
```
next build
```
